# This file stores the flash_commands for each mcus
# Previous version KCONFIG_CONFIG was needed now it is automaticly added when make flash is called
# version : 0.1
# tested/supported flash methods :
#  - make flash
#  - sdcard_flash
#  - flashtool.py
#  - mount/cp/umount (for rp2040)

[m8p]
klipper_section: mcu
action_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -i can0 -u dfa49837feda

[ebb36]
klipper_section: mcu ebb36
action_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -i can0 -u 268805f0659c

[cartographer]
klipper_section: mcu cartographer
is_klipper_fw: false
action_command: ~/cartographer-klipper/scripts/firmware.py -d e3fe63bf9de4 -f CAN
